server:
    port: 8080
    context-path: /apigateway

logging:
    config: ./config/logback.xml

spring:
    aop:
        auto: false
    websocket:
        auto: true
    jooq:
        #请勿动，当使用了ejdbc的配置后，Spring Boot无法识别正确的Dialect
        sqlDialect: Mysql
    mybatis:
        transaction:
            config: method
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    dubbo:
        application:
            name: consumer
        consumer:
            timeout: 30000
        providerRefUrl: dubbo://127.0.0.1:20880