logging:
  config: ./config/logback.xml
spring:
  jooq:
    #请勿动，当使用了ejdbc的配置后，Spring Boot无法识别正确的Dialect
    sqlDialect: Mysql
  dubbo:
      application:
        name: consumer
      consumer:
        timeout: 30000
      providerRefUrl: dubbo://127.0.0.1:20880