server:
  port: 8088
spring:
  dubbo:
    scan: com.hjzgg.apigateway.test.service.demo
    protocol:
      name: dubbo
      port: 20880
    application:
      name: provider
    registry:
      protocol: zookeeper
      address: N/A